version: "3.1"

services:

  nginx:
    build: ./build/docker/dev/nginx
    environment:
      - DEVENV=dev
      - BOXBOAT_ICON=./build/docker/boxboat/nginx.png
      - BOXBOAT_URL=http://dockerhost:48000
    links:
      - dotnet
    ports:
      - "48000:80"
    volumes:
      - ./ui:/var/www

  dotnet:
    build: ./build/docker/dev/dotnet
    environment:
      - DEVENV=dev
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - BOXBOAT_ICON=./build/docker/boxboat/netcore.svg
      - BOXBOAT_URL=http://dockerhost:48010
    links:
      - db
    ports:
      - "48010:5000"
    volumes:
      - ./dotnet:/mnt/dotnet

  db:
    image: mysql:5.7.17
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - BOXBOAT_ICON=./build/docker/boxboat/mysql.png
    ports:
      - "48012:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - BOXBOAT_ICON=./build/docker/boxboat/phpmyadmin.png
      - BOXBOAT_URL=http://dockerhost:48011
    links:
      - db
    ports:
    - "48011:80"
